#!/usr/bin/env bash
# ============================================================================
# new-bridge.sh — scaffold a fresh ODSH Bridge directory tree + config
#
# One command creates your bridge folder with the four zone dirs, a .env
# pointed at that folder, and (optionally) a ready-to-run docker-compose.yaml
# whose bridge mount uses that same folder — no manual path editing.
#
# USAGE:
#   ./scripts/new-bridge.sh C:/ODSH-bridge          # Windows host dir
#   ./scripts/new-bridge.sh /srv/odsh-bridge        # Linux / any dir
#   ./scripts/new-bridge.sh /data/bridge --no-compose   # tree + .env only
#
set -euo pipefail

SRC_TPL="$(cd "$(dirname "$0")/.." && pwd)/bridge-template"
HOST_DIR=""
BIND="/root/ODSH-bridge"
EMIT_COMPOSE=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bind)    BIND="$2"; shift 2;;
    --no-compose) EMIT_COMPOSE=0; shift;;
    -h|--help) sed -n '1,20p' "$0"; exit 0;;
    -*) echo "unknown option: $1"; exit 64;;
    *) HOST_DIR="$1"; shift;;
  esac
done

if [[ -z "$HOST_DIR" ]]; then
  echo 'usage: new-bridge.sh <host-dir> [--host <container-mount>] [--no-compose]'
  echo '  e.g. new-bridge.sh C:/ODSH-bridge   (Windows) or /srv/odsh-bridge (Linux)'
  exit 64;
fi

# container mount path defaults to the classic location unless overridden
if [[ -z "$BIND" ]]; then BIND=/root/ODSH-bridge; fi

say(){ printf '\033[36m[new-bridge]\033[0m %s\n' "$*"; }
ok(){ printf '\033[32m[new-bridge]\033[0m %s\n' "$*"; }
warn(){ printf '\033[33m[new-bridge]\033[0m %s\n' "$*"; }

if [[ -e "$HOST_DIR" && ! -d "$HOST_DIR" ]]; then warn "$HOST_DIR exists but is not a dir"; exit 1; fi
mkdir -p "$HOST_DIR"

if [[ -d "$SRC_TPL/Input" ]]; then
  cp -R "$SRC_TPL/." "$HOST_DIR/"
  rm -f "$HOST_DIR/.gitignore";
  ok "copied four-zone template into $HOST_DIR"
else
  for z in Input Output DSH-Workspace Openclaw-Workspace; do mkdir -p "$HOST_DIR/$z"; done
  ok "created four zones in $HOST_DIR"
fi

# ---- .env at the bridge dir, bridge-path templated in ----
ENVFILE="$HOST_DIR/.env"
cat > "$ENVFILE" <<EOF
# generated by new-bridge.sh — edit what you need; never commit this file
BRIDGE_PATH=$BIND
BRIDGE_RUN_TIMEOUT_MS=15000      # run-command timeout
BRIDGE_ALLOW_ABS_PATHS=false    # keep false: only relative/inside-bridge paths for write/read
OC_HOST=openclaw
OC_PORT=18789
OC_TOKEN=REPLACE_WITH_GATEWAY_TOKEN
DISCORD_CHANNEL_ID=
OC_SEND_SCRIPT=
EOF
ok "wrote $ENVFILE (BRIDGE_PATH=$BIND)"

# ---- optional docker-compose.yaml ----
if [[ $EMIT_COMPOSE = 1 ]]; then
  COMPOSE="$HOST_DIR/docker-compose.yaml"
  cat > "$COMPOSE" <<EOF
services:
  openclaw:
    image: openclaw/openclaw:latest
    container_name: openclaw
    networks: [agent-mesh]
    ports: ["18789:18789"]
    volumes:
      - "$HOST_DIR:$BIND"
    restart: unless-stopped
  deepseek-harness:
    image: deepseek-harness:local
    container_name: deepseek-harness
    networks: [agent-mesh]
    ports: ["127.0.0.1:3080:3080"]
    volumes:
      - "$HOST_DIR:$BIND"
    entrypoint: ["/bin/sh", "$BIND/DSH-Workspace/tools/dsh-entrypoint.sh"]
    restart: unless-stopped
networks:
  agent-mesh:
    driver: bridge
EOF
  ok "wrote $COMPOSE (mount $HOST_DIR -> $BIND)"
fi

echo; ok 'Done. Next:'
echo '  1. edit $ENVFILE : put the real OC_TOKEN (from openclaw.json gateway.auth.token)';
echo '     and, for Cua desktop, set CUA_SSH_USER / run scripts/setup-windows.ps1 on Windows.';
echo '  2. docker compose -f "$COMPOSE" up -d   (or use the repo docker-compose.yml)';
echo '  3. On first boot, approve the DSH deviceId in the OpenClaw Control UI.';