#!/usr/bin/env bash
# ============================================================================
# new-bridge.sh — scaffold an ODSH Bridge: interactive wizard OR one-liner
#
#   ./scripts/new-bridge.sh                       # interactive wizard (visual)
#   ./scripts/new-bridge.sh /srv/odsh-bridge      # non-interactive one-shot
#   ./scripts/new-bridge.sh /srv/odsh-bridge --no-compose
#
# Interactive: walks you through values with a visual prompt; leave a field
# blank to accept the default. Non-interactive keeps prior argv behaviour.
# ============================================================================
set -euo pipefail

SRC_TPL="$(cd "$(dirname "$0")/.." && pwd)/bridge-template"

sep(){ printf "%s\n" "────────────────────────────────────────"; }
h2(){ printf "\n  %s\n" "▸ $1"; }
info(){ printf "  · %s\n" "$1"; }
ok(){ printf "    ✓ %s\n" "$1"; }
warn(){ printf "    ⚠ %s\n" "$1"; }
ask(){ local _v; printf "\n    ◈ %s\n    ▼ %s = " "$2" "$3"; IFS= read -r _v || true; if [ -z "${_v// }" ]; then _v="$3"; fi; eval "$1=$_v"; }
askyn(){ local _a; while true; do printf "\n    ☑ %s %s = " "$2" "(default ${3:-n})"; IFS= read -r _a || true; if [ -z "${_a// }" ]; then _a="$3"; fi; case "$_a" in [yY]) eval "$1=y"; return;; [nN]) eval "$1=n"; return;; esac; done; }

# defaults
HOST_DIR=""; BIND="/root/ODSH-bridge"; OC_NAME="openclaw"; DSH_NAME="deepseek-harness"
OC_PORT="18789"; TOKEN="REPLACE_WITH_GATEWAY_TOKEN"; CHANNEL=""; EMIT_COMPOSE=y; CUA=n; CUA_USER=""; COMPOSE=""

# parse argv
INTERACTIVE=0
while [ $# -gt 0 ]; do
  case "$1" in
    -i|--interactive) INTERACTIVE=1; shift;;
    --no-compose) EMIT_COMPOSE=n; shift;;
    -h|--help) sed -n '1,16p' "$0"; echo; sed -n '17,28p' "$0"; exit 0;;
    *) HOST_DIR="$1"; shift;;
  esac
done

# if interactive OR no dir given -> run wizard
if [ "$INTERACTIVE" = 1 ] || [ -z "$HOST_DIR" ]; then
  sep; printf "\n  ODS Bridge  setup wizard\n"; sep
  h2 "press Enter to keep the default shown in brackets"
  sep
  h2 "1/5 Bridge directory (host path)"
  ask HOST_DIR "bridge host dir" "C:/ODSH-bridge"
  ask BIND "container mount path" "/root/ODSH-bridge"
  h2 "2/5 Service naming"
  ask OC_NAME "OpenClaw service name" "openclaw"
  ask DSH_NAME "DSH service name" "deepseek-harness"
  h2 "3/5 Gateway"
  ask OC_PORT "gateway port" "18789"
  ask TOKEN "OC_TOKEN (blank=placeholder)" "REPLACE_WITH_GATEWAY_TOKEN"
  h2 "4/5 Notifications & options"
  ask CHANNEL "Discord channel id (blank=none)" ""
  askyn EMIT_COMPOSE "generate docker-compose.yaml?" y
  askyn CUA_YN "enable Cua Windows Desktop channel?" n
  if [ "$CUA_YN" = y ]; then ask CUA_USER "Windows SSH username" "$(id -un 2>/dev/null || true)"; fi
  sep; ok "wizard complete."
fi

# sanity
if [ -z "$HOST_DIR" ]; then echo "usage: new-bridge.sh [dir] [--no-compose]"; exit 64; fi

# ---- scaffold the four zones ----
if [ -d "$SRC_TPL/Input" ]; then
  mkdir -p "$HOST_DIR"; cp -R "$SRC_TPL/." "$HOST_DIR/"; rm -f "$HOST_DIR/.gitignore"
  ok "four-zone template copied → $HOST_DIR"
else
  for z in Input Output DSH-Workspace Openclaw-Workspace; do mkdir -p "$HOST_DIR/$z"; done
  ok "four zones created"
fi

# ---- optional SQLite auditing: enabled only if node:sqlite is available (Node >=22.5)
SQLITE_FLAG=0
if node --input-type=module -e "import('node:sqlite').then(()=>process.exit(0)).catch(()=>process.exit(1))" >/dev/null 2>&1; then
  SQLITE_FLAG=1
fi

# ---- .env
ENVFILE="$HOST_DIR/.env"
cat > "$ENVFILE" <<EOF
# ODS Bridge .env (generated by new-bridge.sh)
BRIDGE_PATH=$BIND
BRIDGE_RUN_TIMEOUT_MS=15000
BRIDGE_ALLOW_ABS_PATHS=false
OC_HOST=$OC_NAME
OC_PORT=$OC_PORT
OC_TOKEN=$TOKEN
DISCORD_CHANNEL_ID=$CHANNEL
OC_SEND_SCRIPT=
CUA_SSH_USER=$CUA_USER
# SQLite optional audit side-store (auto: 1 if node:sqlite available)
BRIDGE_SQLITE=$SQLITE_FLAG
EOF
ok ".env written -> $ENVFILE"

# ---- compose (optional)
if [ "$EMIT_COMPOSE" = y ]; then
  COMPOSE="$HOST_DIR/docker-compose.yaml"
  cat > "$COMPOSE" <<EOF
services:
  $OC_NAME:
    image: openclaw/openclaw:latest
    container_name: $OC_NAME
    networks: [agent-mesh]
    ports: ["$OC_PORT:$OC_PORT"]
    volumes: ["$HOST_DIR:$BIND"]
    restart: unless-stopped
  $DSH_NAME:
    image: deepseek-harness:local
    container_name: $DSH_NAME
    networks: [agent-mesh]
    ports: ["127.0.0.1:3080:3080"]
    volumes:
      - "$HOST_DIR:$BIND"
    entrypoint: ["/bin/sh", "$BIND/DSH-Workspace/tools/dsh-entrypoint.sh"]
    restart: unless-stopped
networks:
  agent-mesh:
    driver: bridge
EOF
  ok "docker-compose.yaml written -> $COMPOSE"
fi
sep
echo "Next:"
echo "  1. Set a real OC_TOKEN in $ENVFILE (openclaw.json -> gateway.auth.token)."
if [ -n "$COMPOSE" ]; then echo "  2. docker compose -f \"$COMPOSE\" up -d   (after building deepseek-harness:local)"; else echo "  2. (no compose generated) use the repo docker-compose.yml, or re-run with \"generate compose? y\"."; fi
echo "  3. In the DSH container: node src/oc-client.mjs connect ; approve deviceId."
